name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lint Code Base
        uses: github/super-linter@master
        env:
          VALIDATE_PYTHON_BLACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    strategy:
      matrix:
        python-version: ['3.x', '3.9.0']
    runs-on: ubuntu-latest
    name: "Build package (Python ${{ matrix.python-version }})"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python setup.py install
          pip install -r requirements.txt
          pip install wheel
          python setup.py sdist bdist_wheel
